n_gpu: 1
pin_memory: true
max_epochs: 50
cross_validation: false
csv_logger: false
bootstrap_repeats: 1000

optimizers:
  all:
    AdamW:
      lr: 0.001

models:
  Graph_And_Clinical_Feature_Extractor:
    graph_input_dim: 1280
    graph_hidden_dim: 20
    graph_output_dim: 1
    n_genes: 20
    clinical_numerical_dim: 3
    clinical_categorical_dim: 11
    genomic_embedding_dim: 8
    clinical_embedding_dim: 8 # If clinical_embedding_dim is 0, then the clinical features will not be used.

  Task_Classifier:
    task_dim: 1
    genomic_embedding_dim: 8
    clinical_embedding_dim: 8
    output_dim: 1

datasets:
  project_ids: [TCGA-OV] #, TCGA-LUAD, TCGA-COAD]
  chosen_features:
    gene_ids:
      TCGA-OV: ['TP53', 'CSMD3', 'NF1', 'CDK12', 'FAT3', 'GABRA6', 'RB1', 'MUC1', 'MUC16', 'CD9', 'PAX8', 'WT1', 'BRCA1', 'CDKN2A', 'BRCA2', 'FOXL2', 'ESR1', 'EFTUD2', 'HSPA8', 'STAU1']
    clinical_numerical_ids: ['age_at_diagnosis', 'year_of_diagnosis', 'year_of_birth']
    clinical_categorical_ids:
      - gender
      - race
      - ethnicity
  data_directory: Data/
  cache_directory: Cache/
  target_type: overall_survival
  genomic_type: tpm
  n_threads: 16
  graph_dataset: True
  ppi_score_name: score
  ppi_score_threshold: 0.4
  collect_all_genes: True
  batch_effect_correction: False
  llm: FastESM2_650

datasets_manager:
  type: TCGA_Balanced_Datasets_Manager
  TCGA_BLC:
    train: true
    batch_size: 32
    num_folds: 4
    test_split: 0.2
    num_workers: 4