n_gpu: 1
pin_memory: true
max_epochs: 50
cross_validation: true
bootstrap_repeats: 1000

optimizers:
  feat_ext:
    SGD:
      lr: 0.01
      momentum: 0.9
  clf:
    SGD:
      lr: 0.01
      momentum: 0.9

models:
  Feature_Extractor:
    genomic_dim: 20
    clinical_numerical_dim: 3
    clinical_categorical_dim: 11
    genomic_embedding_dim: 8
    clinical_embedding_dim: 8
  Task_Classifier:
    task_dim: 3
    genomic_embedding_dim: 8
    clinical_embedding_dim: 8
    output_dim: 1

datasets:
  project_ids: [TCGA-OV]
  chosen_features:
    gene_ids:
     
      TCGA-OV: ['TP53', 'CSMD3', 'NF1', 'CDK12', 'FAT3', 'GABRA6', 'RB1', 'MUC1', 'MUC16', 'CD9', 'PAX8', 'WT1', 'BRCA1', 'CDKN2A', 'BRCA2', 'FOXL2', 'ESR1', 'EFTUD2', 'HSPA8', 'STAU1']
    clinical_numerical_ids: ['age_at_diagnosis', 'year_of_diagnosis', 'year_of_birth']
    clinical_categorical_ids:
      - gender
      - race
      - ethnicity
  data_directory: Data/
  cache_directory: Cache/
  target_type: overall_survival
  genomic_type: tpm
  n_threads: 16

datasets_manager:
  type: TCGA_Balanced_Datasets_Manager
  TCGA_BLC:
    train: true
    batch_size: 128
    num_folds: 4
    test_split: 0.2
    num_workers: 4
